### ISSUE TITLE
Input variables listed in the README.me aren't used

### ISSUE THREAD

**Issue by curtisstpierre** [GoogleCloudPlatform/terraform-google-vault#10]
network and subnetwork are listed as input variables for terrform-google-vault but neither of them is used. when attempting to use them they are ignored
```module "vault" {
  source = "github.com/GoogleCloudPlatform/terrform-google-vault"
  project_id           = "${var.project_id}"
  region               = "${var.region}"
  zone                 = "${var.zone}"
  storage_bucket       = "${var.storage_bucket}"
  kms_keyring_name     = "${var.kms_keyring_name}"
  network              = "foo"
  subnetwork           = "bar"
}

**Comment by kalib** [comment]
This module is broken until someone fixes and include the network variables. With the current code, the module would only work for people using a network/subnetwork with the default name.
