### ISSUE TITLE
how does updating vault work this way?

### ISSUE THREAD

**Issue by medyagh** [GoogleCloudPlatform/terraform-google-vault#14]
Thank for the helpful module, I was wondering how would you update/upgrade vault in this model without loosing data and interrupting the service?

**Comment by sethvargo** [comment]
Hi @medyagh 

Thanks for the question. The data is stored in GCS, so you can safely upgrade the Vault version (change the Terraform variable) and then run `terraform plan` and `terraform apply`. This will create a new instance group manager with the newer Vault version, then delete the old instance group manager.

**Comment by priyeshgpatel** [comment]
would this not destroy the bucket on every deployment?
https://github.com/priyeshgpatel/terraform-google-vault/blob/86b003d9b6992e59e060281cc62709b2ccabf7de/examples/vault-on-gce/main.tf#L56
