### ISSUE TITLE
Request for docs: vault service account required permissions

### ISSUE THREAD

**Issue by eljefedelrodeodeljefe** [GoogleCloudPlatform/terraform-google-vault#17]
Hi,
It would be much more seamless to have a note (if I haven't missed) it on the required permissions of the service account from the examples. I am trying one by one currently.

Cheers

**Comment by sethvargo** [comment]
It's documented more deeply in [vault-on-gke](https://github.com/sethvargo/vault-on-gke#additional-permissions).

General required roles (for logging):

- `roles/logging.logWriter`
- `roles/monitoring.metricWriter`
- `roles/monitoring.viewer`

Required roles on storage:

- `roles/storage.legacyBucketReader`
- `roles/storage.objectAdmin`

I'll make a note to document that in this repo during the next refactor. Thanks! 😄
