### ISSUE TITLE
seal-status: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by jasonbisson** [GoogleCloudPlatform/terraform-google-vault#19]
Following solution guide https://cloud.google.com/solutions/using-vault-for-secret-management, but I got the following error when running the vault unseal command.

Error checking seal status: Get https://127.0.0.1:8200/v1/sys/seal-status: x509: certificate signed by unknown authority

I made sure these variables were set, but I must be missing something.

export VAULT_ADDR=https://127.0.0.1:8200
export VAULT_CACERT=/etc/vault/vault-server.ca.crt.pem
export VAULT_CLIENT_CERT=/etc/vault/vault-server.crt.pem
export VAULT_CLIENT_KEY=/etc/vault/vault-server.key.pem

**Comment by jasonwicks** [comment]
I got this issue this morning when trying this for the first time.  Seems like this hasn't been fixed.  I got around it by running the following to unseal:
sudo vault unseal -tls-skip-verify
