### ISSUE TITLE
Getting a project: required field is not set error 

### ISSUE THREAD

**Issue by tazy7** [GoogleCloudPlatform/terraform-google-vault#2]
Hi 

I'm setting the terraform variables on the plan and apply, but getting the following error message. Using default settings on the example repo using the hard coded US based regions and zone works but setting the location variables europe-west2 seems to be causing issues:

`Error applying plan:

4 error(s) occurred:

* google_storage_bucket.vault: 1 error(s) occurred:

* google_storage_bucket.vault: project: required field is not set
* google_service_account.vault-admin: 1 error(s) occurred:

* google_service_account.vault-admin: project: required field is not set
* google_storage_bucket.vault-assets: 1 error(s) occurred:

* google_storage_bucket.vault-assets: project: required field is not set
* module.vault-server.google_compute_firewall.default-ssh: 1 error(s) occurred:

* google_compute_firewall.default-ssh: project: required field is not set`

**Comment by danisla** [comment]
@tazy7 are you running terraform from the module directory or from the [example-vault-on-gce](https://github.com/GoogleCloudPlatform/terraform-google-examples/tree/master/example-vault-on-gce) directory from the examples repository?

Try following the [example here](https://github.com/GoogleCloudPlatform/terraform-google-examples/tree/master/example-vault-on-gce) and set these vars before running terraform:

```
export TF_VAR_region=europe-west2
export TF_VAR_zone=europe-west2-a
```

**Comment by tazy7** [comment]
@danisla Thanks for coming back to me. I'm running terraform from the root of the terraform-google-vault repo. Tried the export variables and still getting the same issue.

**Comment by danisla** [comment]
@tazy7 don't run it from the root of terraform-google-vault repo and instead, run it from the example directory.

**Comment by tazy7** [comment]
I had forgotten to recreate the tfvars file. With running from the correct directory and with the export variables I am now getting the following errors:

3 error(s) occurred:

* module.vault.google_storage_bucket_object.vault-ca-cert: 1 error(s) occurred:

* google_storage_bucket_object.vault-ca-cert: Error, either "content" or "string" must be specified
* module.vault.google_storage_bucket_object.vault-tls-key: 1 error(s) occurred:

* google_storage_bucket_object.vault-tls-key: Error, either "content" or "string" must be specified
* module.vault.google_storage_bucket_object.vault-tls-cert: 1 error(s) occurred:

* google_storage_bucket_object.vault-tls-cert: Error, either "content" or "string" must be specified

**Comment by danisla** [comment]
Have a look at the guide in the README.md for the example, it walks through setting up the KMS keyring for the example:

https://github.com/GoogleCloudPlatform/terraform-google-vault/blob/master/examples/vault-on-gce/README.md

**Comment by tazy7** [comment]
There was an issue with the keyring I was trying to reuse
