### ISSUE TITLE
Updating version to support secrets

### ISSUE THREAD

**Issue by jasonbisson** [GoogleCloudPlatform/terraform-google-vault#21]
Can we update the default version of vault to support secrets? 

In this example the version is 0.9.5.
https://www.youtube.com/watch?v=TEPuFFZdmfA

variable vault_version {
  description = "The version of vault to install."
  default     = "0.9.0"
}

**Comment by dalekurt** [comment]
I see no reason you should not be able to use another version of vault other than the default. In fact, I would like to use the newly releases 0.10.0

**Comment by sethvargo** [comment]
You can update the version using a custom `terraform.tfvars` to override that variable. A future release will update to 1.0+.

https://www.terraform.io/docs/configuration/variables.html
