### ISSUE TITLE
Feature request: Vault HA Cluster with Consul

### ISSUE THREAD

**Issue by dalekurt** [GoogleCloudPlatform/terraform-google-vault#24]
I would like to have Vault in a HA cluster backed by [Consul](https://registry.terraform.io/modules/hashicorp/consul/google/0.0.1) as a module

**Comment by sethvargo** [comment]
You can have a Vault cluster in HA mode [backed by GCS](https://www.vaultproject.io/docs/configuration/storage/google-cloud-storage.html). The goal of this module is to be simple and Google-specific. There are other modules that setup Consul on GCP. You could combine them, but we aren't going to add a Consul-specific mode to this one - sorry!

**Comment by TigerC10** [comment]
It'd be nice to have a configurable option for the backend - something that would let us combine this module with the [Consul module](https://registry.terraform.io/modules/hashicorp/consul/google/latest) more easily.  Absolutely, leave GCS as the backend.
