### ISSUE TITLE
google_storage_bucket_object Errors

### ISSUE THREAD

**Issue by dalekurt** [GoogleCloudPlatform/terraform-google-vault#26]
Terraform version: v0.10.8

I experienced this issue before and thought he fix was related to my values

```
...
kms_keyring_name = "vault"
kms_key_name = "vault-init"
...
```

However, I'm doing fresh deployment and came across the issue once again, double-checked my terraform.tfvars file to make sure I have the correct values and as you can see they are correct. 

Anyone else having this issue and what it related to, did I miss a step?

```
Error: Error applying plan:

4 error(s) occurred:

* module.vault.google_storage_bucket_object.vault-tls-key: 1 error(s) occurred:

* google_storage_bucket_object.vault-tls-key: Error, either "content" or "source" must be specified
* module.vault.google_storage_bucket_object.vault-sa-key: 1 error(s) occurred:

* google_storage_bucket_object.vault-sa-key: Error, either "content" or "source" must be specified
* module.vault.google_storage_bucket_object.vault-ca-cert: 1 error(s) occurred:

* google_storage_bucket_object.vault-ca-cert: Error, either "content" or "source" must be specified
* module.vault.google_storage_bucket_object.vault-tls-cert: 1 error(s) occurred:

* google_storage_bucket_object.vault-tls-cert: Error, either "content" or "source" must be specified
```

**Comment by dalekurt** [comment]
I updated the terraform-google-vault to allow the variable for the KMS keyring name and key name. This errors was a result of the mismatch from the terraform.tfvars and the module.

**Comment by ferrier1** [comment]
I am also receiving this error. Can you please elaborate on the fix?

I have tried adding kms_key_name = "vault-init" to tfvars as well as variables.tf with no success.
