### ISSUE TITLE
terraform init failing with Invalid default value for variable "tls_ca_subject"

### ISSUE THREAD

**Issue by narendrakadali** [GoogleCloudPlatform/terraform-google-vault#30]
terraform plan
Error: Invalid default value for variable
  on ../../variables.tf line 76, in variable "tls_ca_subject":
  76:   default = {
  77:     common_name         = "Example Inc. Root"
  78:     organization        = "Example, Inc"
  79:     organizational_unit = "Department of Certificate Authority"
  80:     street_address      = ["123 Example Street"]
  81:     locality            = "The Intranet"
  82:     province            = "CA"
  83:     country             = "US"
  84:     postal_code         = "95559-1227"
  85:   }
This default value is not compatible with the variable's type constraint: all
map elements must have the same type.

changing street_address type to String fixing the issue.

**Comment by darnold-harness** [comment]
Seeing same issue, any update?

**Comment by jasonwicks** [comment]
I received this error also.  I noticed that I had downloaded an "alpha" version of terraform.  The script used to download terraform needs to be modified to also exclude alpha versions:

ie. change this line in the script located here (https://goo.gl/yZS5XU):
LATEST_URL=$(curl -sL https://releases.hashicorp.com/terraform/index.json | jq -r '.versions[].builds[].url' | sort --version-sort | egrep -v 'rc|beta' | egrep 'linux.*amd64' |tail -1)

to

LATEST_URL=$(curl -sL https://releases.hashicorp.com/terraform/index.json | jq -r '.versions[].builds[].url' | sort --version-sort | egrep -v 'rc|beta|alpha' | egrep 'linux.*amd64' |tail -1)

I manually downloaded the file (https://goo.gl/yZS5XU) and modified the script as above and executed (after removing old version of terraform)

I manually removed the file and installed the lasted "GA" version - which for me was v0.11.11.

**Comment by darnold-harness** [comment]
> I received this error also. I noticed that I had downloaded an "alpha" version of terraform. The script used to download terraform needs to be modified to also exclude alpha versions:
> 
> ie. change this line in the script located here (https://goo.gl/yZS5XU):
> LATEST_URL=$(curl -sL https://releases.hashicorp.com/terraform/index.json | jq -r '.versions[].builds[].url' | sort --version-sort | egrep -v 'rc|beta' | egrep 'linux.*amd64' |tail -1)
> 
> to
> 
> LATEST_URL=$(curl -sL https://releases.hashicorp.com/terraform/index.json | jq -r '.versions[].builds[].url' | sort --version-sort | egrep -v 'rc|beta|alpha' | egrep 'linux.*amd64' |tail -1)
> 
> I manually downloaded the file (https://goo.gl/yZS5XU) and modified the script as above and executed (after removing old version of terraform)
> 
> I manually removed the file and installed the lasted "GA" version - which for me was v0.11.11.

yeah, I noticed the same; but, your fix might not work for the long term. Terraform 0.12 is soon to be released GA and when it does this tool will still be broken. Should probably just pin the version rather than scripting it. Just a thought.
