### ISSUE TITLE
Missing Permissions and Service Account keys

### ISSUE THREAD

**Issue by dboshardy** [GoogleCloudPlatform/terraform-google-vault#37]
I've been trying to get `vault-on-gce` running in a brand new project I am owner of.  However, I've run into several issues.  For instance, I've had to add several Roles to the created Service Account (`vault-admin`).  Additionally, because of the lack of dependencies in the `vault-server` module, the startup script for the GCE instance fails as the service account used on that instance does not yet have the permissions to authenticate and upload to GStorage.  So every time I've run this, I've had to rolling restart the instance group.

Similarly, in the steps laid out [here](https://cloud.google.com/solutions/using-vault-for-secret-management#deploying_vault_using_terraform), I've found that I cannot run this command:
```
JWT_TOKEN=$(gcloud beta iam service-accounts sign-jwt login_request.json \
    signed_jwt.json \
    --iam-account=${SERVICE_ACCOUNT} && cat signed_jwt.json)
```

without running `gcloud auth login` and giving myself the Service Account Token Creator role.  

After resolving that, this command fails:

```
vault write -field=token auth/gcp/login role=dev-role jwt=${JWT_TOKEN} > ~/.vault-token
```
with an error stating the key used to sign the JWT Token does not exist.  It looks like the JWT was signed using a service account key that doesn't exist and is not visible on the Service Account UI in the cloud console.

This is the redacted error:

```
* service account key 'projects/{PROJECT}/serviceAccounts/vault-admin@{PROJECT}.iam.gserviceaccount.com/keys/{NON_EXISTANT_KEY_ID}' does not exist: googleapi: Error 403: Permission iam.serviceAccountKeys.get is required to perform this operation on service account key projects/{PROJECT}/serviceAccounts/vault-admin@{PROJECT}.iam.gserviceaccount.com/keys/{NON_EXISTANT_KEY_ID}., forbidden
```

How can I resolve this issue?

**Comment by dboshardy** [comment]
I should add. I also have given both myself and the service account the Service Account Key Admin role.

**Comment by sethvargo** [comment]
Hi @dboshardy 

I've updated the README with [additional permissions](https://github.com/GoogleCloudPlatform/terraform-google-vault#additional-permissions) you might need for different Vault backends.

The default installation includes the most minimal set of permissions to run Vault. Certain plugins may require more permissions, which you can grant to the service account using service_account_project_additional_iam_roles:

### GCP auth method
The GCP auth method requires the following additional permissions:

```
roles/iam.serviceAccountKeyAdmin
```

### GCP secrets engine
The GCP secrets engine requires the following additional permissions:

```
roles/iam.serviceAccountKeyAdmin
roles/iam.serviceAccountAdmin
```

### GCP KMS secrets engine
The GCP secrets engine permissions vary. There are examples in the secrets engine documentation.
