### ISSUE TITLE
Fields for google provider [REMOVED]

### ISSUE THREAD

**Issue by jorge0136** [GoogleCloudPlatform/terraform-google-vault#38]
Note this issue is related to #34 but I am getting a slightly different error. 

**Problem**: When attempting to use the [vault-on-gce example](https://github.com/GoogleCloudPlatform/terraform-google-vault/tree/master/examples/vault-on-gce) I get the following errors after executing `terraform plan`. 

```
Error: module.vault.module.vault-server.google_compute_instance_group_manager.default: "auto_healing_policies.0.initial_delay_sec": [REMOVED] This field is in beta. Use it in the the google-beta provider instead. See https://terraform.io/docs/providers/google/provider_versions.html for more details.

Error: module.vault.module.vault-server.google_compute_instance_group_manager.default: "rolling_update_policy": [REMOVED] This field is in beta. Use it in the the google-beta provider instead. See https://terraform.io/docs/providers/google/provider_versions.html for more details.

Error: module.vault.module.vault-server.google_compute_instance_template.default: "network_interface.0.address": [REMOVED] Please use network_ip
```

**Attempted fixes**: 

1)  I attempted to execute the terraform execution in the context of google cloud shell to see if there was perhaps something unique about my local environment but that did not change the outcome. 

2) Reading the error and associated documentation link it appears to me that I should be able to switch from the `google` provider to the `google-beta` provider to resolve this issue. I edited the [following](https://github.com/GoogleCloudPlatform/terraform-google-vault/blob/b11e8f44bbb28c6936a703fba6863ad5b681c772/examples/vault-on-gce/main.tf#L29) line to be `google-beta`.

This did not resolve the issue. I still see the `google` provider being provisioned during `terraform init`. I am fairly new to terraform and in reading about the plugin system it seems there isn't a straightforward way to remove old providers. 

To help mitigate the potential of an old `google` version of the provider being the issue I started over again in a new folder, as terraform will provision providers for only the [current working directory](https://www.terraform.io/docs/configuration/providers.html#initialization).  However when I execute `terraform init` I still see the google provider being initialized.

```
* provider.google: version = "~> 2.0"
* provider.google-beta: version = "~> 2.0"
```
Attempting `terraform plan` after the initialization in a new folder does still trigger the same error.

I searched through the remainder of the codebase in the hope that I would find a call to the original google provider but I haven't been able to find anything. This is literally my first time using terraform, I very well may be chasing the wrong issue. 

**System information**: 

* osx: 10.14.3
* Terraform: v0.11.11

**Comment by sethvargo** [comment]
Working on an update. Pin to < 2.0 for now please:

```hcl
provider "google" {
  version = "~> 1.0"
}

provider "google-beta" {
  version = "~> 1.0"
}
```
