### ISSUE TITLE
examples/vault-on-gcp failing now

### ISSUE THREAD

**Issue by rwillard** [GoogleCloudPlatform/terraform-google-vault#7]
I ran the terraform scripts previously 2 weeks ago and everything worked fine. Running them again today I end up with variations of 
```
* module.vault.data.external.sa-key: data.external.sa-key: failed to execute "/home/robert/terraform-google-vault/examples/vault-on-gce/.terraform/modules/85d849467b2166b96780a48cb9f
6e5d7/get_sa_key.sh": fork/exec /home/robert/terraform-google-vault/examples/vault-on-gce/.terraform/modules/85d849467b2166b96780a48cb9f6e5d7/get_sa_key.sh: no such file or directory
```
I've verified that these scripts exist at the exact location specified. Any idea what's wrong?

**Comment by danisla** [comment]
@rwillard are you running Terraform on linux? I think something changed in the linux build for terraform that broke the external provider.

**Comment by rwillard** [comment]
@danisla I'm running the commands from GCP cloud shell. Documentation says it's a Debian based Linux OS. I am following this guide `https://cloud.google.com/solutions/using-vault-for-secret-management`.

**Comment by rwillard** [comment]
@danisla I'm running the commands from GCP cloud shell. Documentation says it's a Debian based Linux OS. I am following this guide `https://cloud.google.com/solutions/using-vault-for-secret-management`.

**Comment by danisla** [comment]
@rwillard in the tutorial step 6 for configuring cloud shell with terraform, run this instead to revert to v0.10.7:

```
curl -L https://goo.gl/wRnGxT -o ${HOME}/.tfdocker
source ${HOME}/.tfdocker
```

This is a temporary work around until the terraform issue is resolved.

**Comment by danisla** [comment]
@rwillard in the tutorial step 6 for configuring cloud shell with terraform, run this instead to revert to v0.10.7:

```
curl -L https://goo.gl/wRnGxT -o ${HOME}/.tfdocker
source ${HOME}/.tfdocker
```

This is a temporary work around until the terraform issue is resolved.

**Comment by danisla** [comment]
@rwillard in the tutorial step 6 for configuring cloud shell with terraform, run this instead to revert to v0.10.7:

```
curl -L https://goo.gl/wRnGxT -o ${HOME}/.tfdocker
source ${HOME}/.tfdocker
```

This is a temporary work around until the terraform issue is resolved.

**Comment by rwillard** [comment]
I'll run it again to be sure, and post results here. But I did try yesterday with the 0.10.7 version of the docker image. Let me make sure though.

**Comment by rwillard** [comment]
@danisla I went through all the steps in a new project, and used your workaround to use the 0.10.7 image, but I got the same results.

```
* module.vault.data.external.vault-tls-key-encrypted: data.external.vault-tls-key-encrypted: failed to execute "/home/robert/terraform-google-vault/examples/vault-on-gce/.terraform/m
odules/85d849467b2166b96780a48cb9f6e5d7/encrypt_file.sh": fork/exec /home/robert/terraform-google-vault/examples/vault-on-gce/.terraform/modules/85d849467b2166b96780a48cb9f6e5d7/encr
ypt_file.sh: no such file or directory
* module.vault.data.external.vault-tls-cert-encrypted: data.external.vault-tls-cert-encrypted: failed to execute "/home/robert/terraform-google-vault/examples/vault-on-gce/.terraform
/modules/85d849467b2166b96780a48cb9f6e5d7/encrypt_file.sh": fork/exec /home/robert/terraform-google-vault/examples/vault-on-gce/.terraform/modules/85d849467b2166b96780a48cb9f6e5d7/en
crypt_file.sh: no such file or directory
* module.vault.data.external.sa-key: data.external.sa-key: failed to execute "/home/robert/terraform-google-vault/examples/vault-on-gce/.terraform/modules/85d849467b2166b96780a48cb9f
6e5d7/get_sa_key.sh": fork/exec /home/robert/terraform-google-vault/examples/vault-on-gce/.terraform/modules/85d849467b2166b96780a48cb9f6e5d7/get_sa_key.sh: no such file or directory
```
Thank you for your help with this!

**Comment by ericnorris** [comment]
I think this issue may be related to this https://github.com/hashicorp/docker-hub-images/pull/23 - the scripts in this repo use `/bin/bash` in the shebang ([example](https://github.com/GoogleCloudPlatform/terraform-google-vault/blob/61d2d8d95961e11c64e009b5ee95d2d2ab722fb7/get_sa_key.sh#L1)) which isn't in the docker image.

**Comment by danisla** [comment]
@ericnorris yup that's it. The image doesn't have bash in it anymore. Quick fix is to just download terraform and install it in cloud shell. I'll work on updating the tutorial to make it compatible with the docker image.

**Comment by danisla** [comment]
The tutorial has been updated to install Terraform locally rather than using the docker image.
